### ISSUE TITLE
`ERROR:  While executing gem ... (Gem::Package::FormatError)`

### ISSUE THREAD

**Issue by dentarg** [fedora-ruby/gem-compare#37]
```bash
$ docker run --rm -it -w /tmp ruby:3.1 bash
root@426e763eec1d:/tmp# gem install gem-compare -v 1.2.1
Fetching rainbow-3.1.1.gem
Fetching gem-compare-1.2.1.gem
Fetching gemnasium-parser-0.1.9.gem
Fetching diffy-3.4.2.gem
Successfully installed rainbow-3.1.1
Successfully installed gemnasium-parser-0.1.9
Successfully installed diffy-3.4.2
Successfully installed gem-compare-1.2.1
4 gems installed

root@426e763eec1d:/tmp# gem compare nokogiri 1.13.6 1.13.8
Fetching nokogiri-1.13.6-x86_64-linux.gem
ERROR:  While executing gem ... (Gem::Package::FormatError)
    No such file or directory @ rb_sysopen - /tmp/d20220730-17-pm5je1/nokogiri-1.13.6.gem
```

with some debug output

```bash
root@426e763eec1d:/tmp# cat <<EOF > gemrc
:backtrace: true
:verbose: :really
EOF
root@426e763eec1d:/tmp# gem compare --config-file ./gemrc nokogiri 1.13.6 1.13.8
gem-compare in 1.2.1
Expanding versions ["1.13.6", "1.13.8"]...
Expanded versions: ["1.13.6", "1.13.8"]
GET https://rubygems.org/specs.4.8.gz
304 Not Modified
Downloading gem nokogiri-1.13.6.gem
GET https://rubygems.org/gems/nokogiri-1.13.6.gem
Fetching nokogiri-1.13.6.gem
200 OK
nokogiri-1.13.6.gem downloaded.
Downloading gem nokogiri-1.13.8-x86_64-linux.gem
GET https://rubygems.org/gems/nokogiri-1.13.8-x86_64-linux.gem
Fetching nokogiri-1.13.8-x86_64-linux.gem
200 OK
ERROR:  While executing gem ... (Gem::Package::FormatError)
    No such file or directory @ rb_sysopen - /tmp/d20220730-28-r1xh3r/nokogiri-1.13.8.gem
    /usr/local/lib/ruby/3.1.0/rubygems/package.rb:611:in `rescue in verify'
    /usr/local/lib/ruby/3.1.0/rubygems/package.rb:588:in `verify'
    /usr/local/lib/ruby/3.1.0/rubygems/package.rb:573:in `spec'
    /usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:289:in `use_package'
    /usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:233:in `download_package'
    /usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:221:in `get_package'
    /usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:83:in `block in compare_versions'
    /usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:81:in `each'
    /usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:81:in `compare_versions'
    /usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/commands/compare_command.rb:100:in `execute'
    /usr/local/lib/ruby/3.1.0/rubygems/command.rb:323:in `invoke_with_build_args'
    /usr/local/lib/ruby/3.1.0/rubygems/command_manager.rb:180:in `process_args'
    /usr/local/lib/ruby/3.1.0/rubygems/command_manager.rb:149:in `run'
    /usr/local/lib/ruby/3.1.0/rubygems/gem_runner.rb:53:in `run'
    /usr/local/bin/gem:21:in `<main>'
```

**Comment by strzibny** [comment]
Isn't this happening simply because the installation of the gem failed?

**Comment by dentarg** [comment]
From the logs it looks something didn't expect to get the -linux version

**Comment by dentarg** [comment]
I just had this problem consistently on Ruby 3.2 (`gem compare sqlite3 2.1.1 2.2.0`) but by using Ruby 3.3.5 it went away. More details in https://github.com/dentarg/gem-compare/issues/10.

I think we can close it for now.

**Comment by strzibny** [comment]
Great, then let's move on. Thanks.
